[package]
name = "lunar_lander"
version = "0.1.0"
authors = ["Bruno Muciño <mucinoab@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
rand = "0.8.3"
simdnoise = "3.1.6"
ncollide2d = "0.27.0"
